### ISSUE TITLE
Add support for collections

### ISSUE THREAD

**Issue by matus12** [Kentico/kontent-management-sdk-js#43]
### Motivation

We have added new endpoints to the Management API for collections and we would like it to be covered in the SDK.

### Proposed solution

The SDK should include the functionality of the new endpoints for collections:

- get all collections
- patch collections
- get variants by collections

### Additional context

The endpoints that were added: 

- `GET /{projectId}/collections`
  - returns all collections in the project, no pagination
  - `last_modified` may be null
  - sample response: 
```yaml
{
    "last_modified": "2021-05-13T14:44:51.1526626Z",
    "collections": [
        {
            "id": "00000000-0000-0000-0000-000000000000",
            "name": "Default",
            "codename": "default"
        },
        {
            "id": "8af21c1b-0bf2-4af4-a26d-5010a4a04339",
            "name": "Development",
            "codename": "development",
            "external_id": "custom-external-id"
        },
       {
            "id": "64c2783c-9982-4ee0-affc-59bbb69a4eff",
            "name": "Marketing",
            "codename": "marketing"
        }
    ]
}
```
- `PATCH /{projectId}/collections`
  - accepts array of operations, similar to [asset folders](https://docs.kontent.ai/reference/management-api-v2#tag/Assets):

    - `addInto` - to create a new collection, this operation also contains:
      - `value`:
        - `name` (required)
        - `codename` (if not set, it will be generated. Must be unique)
        - `externalId` (optional, must be unique)
      - `after/before` (optional, contains identifier of another collection. If it is set, the new collection will be added before/after the specified collection. See i.e. [taxonomy patch](https://docs.kontent.ai/reference/management-api-v2#operation/retrieve-a-taxonomy-group) for example). 
      
    - `replace` - to modify a collection. Only collection name can be updated this way, because codenames currently cannot be updated. This operation must also contain:
      - `reference` - identifier of the collection that will be changed
      - `property_name`
      - `value`
      
    - `move` - to reorder collections. This operation must contain:
      - `reference` - identifier of the collection that will be changed
      - `before` or `after` parameter, saying where the given collection should be moved.
      
    - `remove` - to delete a collection:
      - must contain `reference` - identifier of the collection that will be deleted
      - only an empty collection (that does not have any items) can be deleted
      - default collection cannot be deleted
      - returns code 204 (as in other entities)
  - returns list of all collections - same format as in `GET /{projectId}/collections`
  - sample request body containing all operations: 
```yaml
[
  {
    "op": "addinto",
    "value": {
      "external_id": "another-collection",
      "name": "Another collection",
      "codename": "another_collection_codename"
    },
    "after": {
      "codename": "second_collection"
    }
  },
  {
    "op": "move",
    "reference" : {
      "codename": "important_collection"
    },
    "before": {
      "codename": "first_collection"
    }
  },
  {
    "op": "remove",
    "reference" : {
      "codename": "extra_collection"
    }
  },
  {
    "op": "replace",
    "property_name": "name",
    "value":"A new name",
    "reference" : {
      "codename": "second_collection"
    }
  }
]
```    
- `GET /{projectId}/collections/{identifier}/variants`
  - returns paginated list of variants that are in the specified collection similar to list [language variants by type](https://docs.kontent.ai/reference/management-api-v2#operation/list-language-variants-by-type)
  - the `identifier` of the collection can be: 
    - `{itemId}`
    - `external-id/{externalId}`
    - `codename/{codename}`
  - sample response: 
```yaml
{
  "variants": [
    {
      "elements": [
        {
          "element": {
            "id": "7117ada8-409f-442c-9d9c-41424980c0a0"
          },
          "value": "Compellingly Develop Scalable Scenarios."
        },
        {
          "element": {
            "id": "3ab5ca51-b317-459b-b34f-401c7cc350cd"
          },
          "value": [
            {
              "id": "7c0dd64a-239d-4ff8-8e9c-29ee09759160"
            }
          ]
        }
      ],
      "workflow_step": {
        "id": "502a6d13-4e33-4e14-905b-c784217ddc7d"
      },
      "item": {
        "id": "3f4a537b-b755-49b0-bb09-9df63ae92404"
      },
      "language": {
        "id": "00000000-0000-0000-0000-000000000000"
      },
      "last_modified": "2021-05-07T08:34:00.7956931Z"
    }
  ],
  "pagination": {
    "continuation_token": null,
    "next_page": null
  }
}
```
